spring:
  datasource:
    url: jdbc:h2:mem:apiDB
    username: user
    password: pass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static